language: node_js
node_js:
- '10.5.0'
branches:
  only:
  - master
  - develop
notifications:
    slack: academy2018:0hVvpbtAXM1gcBdegKbDII64
before_script:
- cd frontend
- npm install
script:
- npx ng build --prod
after_success:
  'find dist/polyglot/ -type f -exec curl -u $FTP_USERNAME:$FTP_PASSWORD --ftp-create-dirs -T {} $FTP_SERVER_HOST{} ";"'