language: node_js
node_js:
- '10.5.0'
branches:
  only:
  - master
  - develop
notifications:
    slack: academy2018:0hVvpbtAXM1gcBdegKbDII64
before_script:
- cd frontend
- npm install
script:
- npx ng build --prod
deploy:
  skip_cleanup: true
  provider: script
  script: node ../deploy.js
  on:
    branch: develop