language: node_js
node_js:
- '10.5.0'
branches:
  only:
  - master
  - develop
notifications:
    slack: academy2018:0hVvpbtAXM1gcBdegKbDII64
before_script:
- cd frontend
- npm install
- npm install -g gulp
- npm install vinyl-ftp gulp-util minimist --save-dev
- npm link gulp
script:
- npx ng build --prod
after_success:  
  - gulp --gulpfile ../deploy.js deploy --user $USERNAME --password $PASSWORD